<!doctype html><html lang="en-US"><!--  --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- / -->
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">  <link media="all" href="../../wp-content/cache/autoptimize/4/css/autoptimize_dc56928889f08ceb40a4520f8ece953b.css" rel="stylesheet" /><title>C++ &#8211; Error handling considerations &#8211; free-tor-game.com</title> <script>MathJax = {
  tex: {
    inlineMath: [['$','$'],['\\(','\\)']], 
    processEscapes: true
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore|editor-rich-text'
  }
};</script> <link rel='dns-prefetch' href='http://cdn.jsdelivr.net/' /><link rel='dns-prefetch' href='http://cdnjs.cloudflare.com/' /><link rel='dns-prefetch' href='http://stackpath.bootstrapcdn.com/' /><link rel='dns-prefetch' href='http://s.w.org/' /><link rel='stylesheet' id='highlight-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/vs2015.min40df.css?ver=5.6' type='text/css' media='all' /><link rel='stylesheet' id='bootstrap-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.mina352.css?ver=4.1.3' type='text/css' media='all' /><link rel='stylesheet' id='icons-css'  href='../../../stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min40df.css?ver=5.6' type='text/css' media='all' /> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.minb8ff.js?ver=1.12.4' id='jquery-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.minc9a3.js?ver=11.2.0' id='highlight-js'></script>            <script>hljs.highlightAll();</script> <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1731162805004860" crossorigin="anonymous"></script></head><body class="software-template-default single single-software postid-1071880 no-sidebar"><div id="page" class="site"> <a class="skip-link screen-reader-text" href="#content">Skip to content</a><header id="topnav" class="sticky-top"><nav class="navbar navbar-expand-md navbar-light bg-light" role="navigation"> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <a class="navbar-brand" href="#">free-tor-game.com</a><div id="navbar-primary" class="collapse navbar-collapse"><ul id="menu-primary-top-menu" class="nav navbar-nav"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-192" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children dropdown menu-item-192 nav-item"><a title="Tools" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-192">Tools</a><ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-192" role="menu"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-193" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-193 nav-item"><a title="ARFCN-Frequency Converter" href="../../3gpp-arfcn-frequency-converter/" class="dropdown-item">ARFCN-Frequency Converter</a></li></ul></li><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-2301" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2301 nav-item"><a title="Contact Us" href="../../contact/" class="nav-link">Contact Us</a></li></ul></div></nav></header><div id="content" class="site-content"><div id="primary" class="content-area"><main id="main" class="site-main"><div id="main-container" class="container"><div id="main-row" class="row"><div id="main-col" class="col-12"><article id="post-1071880" class="post-1071880 software type-software status-publish hentry category-software tag-c tag-coding-style tag-exceptions tag-paradigms"><div class="row"><div class="col-12 col-md-8"><header class="entry-header"><h1 class="entry-title text-danger">C++ &#8211; Error handling considerations</h1></header><p style='font-size:1.2em'><span class="mr-2 badge badge-success">c</span><span class="mr-2 badge badge-info">coding-style</span><span class="mr-2 badge badge-warning">exceptions</span><span class="mr-2 badge badge-primary">paradigms</span></p><div class="entry-content"><p><strong>The problem:</strong></p><p>Since long time, I am worried about the <code>exceptions</code> mechanism, because I feel it does not really resolve what it should.</p><p>CLAIM: There are long debates outside about this topic, and most of them struggle at comparing <code>exceptions</code> vs returning an error code. This is definitively not the topic here.</p><p>Trying to define an error, I would agree with CppCoreGuidelines, from Bjarne Stroustrup &amp; Herb Sutter</p><blockquote><p><strong>An error means that the function cannot achieve its advertised purpose</strong></p></blockquote><p>CLAIM: The <code>exception</code> mechanism is a language semantic for handling errors.</p><p>CLAIM: To me, there is &#34;no excuse&#34; to a function for not achieving a task: Either we wrongly defined pre/post conditions so the function cannot ensure results, or some specific exceptional case is not considered important enough for spending time in developing a solution. Considering that, IMO, the difference between normal code and error code handling is (before implementation) a very subjective line.</p><p>CLAIM: Using exceptions to indicate when a pre or post condition is not keep is another purpose of the <code>exception</code> mechanism, mainly for debugging purpose. I do not target this usage of <code>exceptions</code> here.</p><p>In many books, tutorials and other sources, they tend to show error handling as a quite objective science, that is solved with <code>exceptions</code> and you just need to <code>catch</code> them for having a robust software, able to recover from any situation. But my several years as a developer make me to see the problem from a different approach:</p><ul><li>Programmers tends to simplify their task by throwing exceptions when the specific case seem too rare to be implemented carefully. Typical cases of this are: out of memory issues, disk full issues, corrupted file issues, etc. This might be sufficient, but is not always decided from an architectural level.</li><li>Programmers tends not reading carefully documentation about exceptions in libraries, and are usually not aware of which and when a function throws. Furthermore, even when they know, they don&#39;t really manage them.</li><li>Programmers tends not catching exceptions early enough, and when they do, it is mostly to log and throw further. (refer to first point).</li></ul><p>This has two consequences:</p><ol><li>Errors happening frequently are detected early in development and debugged (which is good).</li><li>Rare exceptions are not managed and make the system to crash (with a nice log message) at the user home. Some times the error is reported, or not even.</li></ol><p>Considering that, IMO the main purpose of an error mechanism should be:</p><ol><li>Make visible in code where some specific case is not managed.</li><li>Communicate the issue runtime to related code (at least the caller) when this situation happens.</li><li>Provides recovery mechanisms</li></ol><p>The main flaw of the <code>exception</code> semantic as an error handling mechanism is IMO: it is easy to see where a <code>throw</code> is in the source code, but absolutely not evident to know if a specific function could throw by looking at the declaration. This bring all the problem that I introduced above.</p><blockquote><p>The language do not enforce and check the error code as strictly as it make for other aspects of the language (e.g. strong types of variables)</p></blockquote><p><strong>A try for solution</strong></p><p>In the intention of improving this, I developed a very simple error handling system, which tries to put the error handling at the same level of importance than the normal code.</p><p>The idea is:</p><ul><li>Each (relevant) function receive a reference to a <code>success</code> very light object, and may set it to an error status in case. The object is very light until a error with text is saved.</li><li>A function is encouraged to skip its task if the object provided contain already an error.</li><li>An error must never be override.</li></ul><p>The full design obviously consider thoroughly each aspect (about 10 pages), also how to apply it to OOP.</p><p>Example of the <code>Success</code> class:</p><pre><code>class Success
{
public:
    enum SuccessStatus
    {
        ok = 0,             // All is fine
        error = 1,          // Any error has been reached
        uninitialized = 2,  // Initialization is required
        finished = 3,       // This object already performed its task and is not useful anymore
        unimplemented = 4,  // This feature is not implemented already
    };

    Success(){}
    Success( const Success&amp; v);
    virtual ~Success() = default;
    virtual Success&amp; operator= (const Success&amp; v);

    // Comparators
    virtual bool operator==( const Success&amp; s)const { return (this-&gt;status==s.status &amp;&amp; this-&gt;stateStr==s.stateStr);}
    virtual bool operator!=( const Success&amp; s)const { return (this-&gt;status!=s.status || this-&gt;stateStr==s.stateStr);}

    // Retrieve if the status is not &#34;ok&#34;
    virtual bool operator!() const { return status!=ok;}

    // Retrieve if the status is &#34;ok&#34;
    operator bool() const { return status==ok;}

    // Set a new status
    virtual Success&amp; set( SuccessStatus status, std::string msg=&#34;&#34;);
    virtual void reset();

    virtual std::string toString() const{ return stateStr;}
    virtual SuccessStatus getStatus() const { return status; }
    virtual operator SuccessStatus() const { return status; }

private:
    std::string stateStr;
    SuccessStatus status = Success::ok;
};
</code></pre><p>Usage:</p><pre><code>double mySqrt( Success&amp; s, double v)
{
    double result = 0.0;
    if (!s) ; // do nothing
    else if (v&lt;0.0) s.set(Error, &#34;Square root require non-negative input.&#34;);
    else result = std::sqrt(v);
    return result;
}

Success s;
mySqrt(s, 144.0);
otherStuff(s);
saveStuff(s);
if (s) /*All is good*/;
else cout &lt;&lt; s &lt;&lt; endl;
</code></pre><p>I used that in many of my (own) code and it force the programmer (me) to think further about possible exceptional cases and how to solve them (good). However, it has a learning curve and don&#39;t integrate well with code that do now use it.</p><p><strong>The question</strong></p><p>I would like to understand better the implications of using such a paradigm in a project:</p><ul><li>Is the premise to the problem correct? or Did I missed something relevant?</li><li>Is the solution a good architectural idea? or the price is too high?</li></ul><hr/><p>EDIT:</p><p>Comparison between methods:</p><pre><code>//Exceptions:

    // Incorrect
    File f = open(&#34;text.txt&#34;); // Could throw but nothing tell it! Will crash
    save(f);

    // Correct
    File f;
    try
    {
        f = open(&#34;text.txt&#34;);
        save(f);
    }
    catch( ... )
    {
        // do something 
    }

//Error code (mixed):

    // Incorrect
    File f = open(&#34;text.txt&#34;); //Nothing tell you it may fail! Will crash
    save(f);

    // Correct
    File f = open(&#34;text.txt&#34;);
    if (f) save(f);

//Error code (pure);

    // Incorrect
    File f;
    open(f, &#34;text.txt&#34;); //Easy to forget the return value! will crash
    save(f);

    //Correct
    File f;
    Error er = open(f, &#34;text.txt&#34;);
    if (!er) save(f);

//Success mechanism:

    Success s;
    File f;
    open(s, &#34;text.txt&#34;);
    save(s, f); //s cannot be avoided, will never crash.
    if (s) ... //optional. If you created s, you probably don&#39;t forget it.
</code></pre></div>     <div id="comments" class="comments-area"><div class="row"><div class="col-12"><div class="mt-3 border-bottom border-success"><h4 class="text-success"><i class='fa fa-check-circle text-success mr-3'></i><span>Best Answer</span></h4></div><div class='bg-transparent mb-3'><p><strong>Error-handling</strong> is perhaps the hardest portion of a program.</p><p>In general, realizing that there is an error condition is easy; however signalling it in a way that cannot be circumvented and handling it appropriately (see <a href="https://en.wikipedia.org/wiki/Exception_safety" rel="noreferrer">Abrahams&#39; Exception Safety levels</a>) is really hard.</p><p>In C, signalling errors is done by a return code, which is isomorphic to your solution.</p><p>C++ introduced exceptions because of the <em>short-coming</em> of such an approach; namely, it only works if callers remember to check whether an error occurred or not and fails apart horribly otherwise. Whenever you find yourself saying &#34;It&#39;s OK as long as every time...&#34; you have a problem; humans are not that meticulous, even when they care.</p><p>The problem, however, is that exceptions have their own issues. Namely, invisible/hidden control flow. This was intended: hiding the error case so that the logic of the code is not obfuscated by the error handling boilerplate. It makes the &#34;happy path&#34; much clearer (and fast!), at the cost of making the error paths nigh inscrutable.</p><hr/><p>I find it interesting to look at how other languages approach the issue:</p><ul><li>Java has checked exceptions (and unchecked ones),</li><li>Go uses error codes/panics,</li><li>Rust uses <a href="https://doc.rust-lang.org/std/result/enum.Result.html" rel="noreferrer">sum types</a>/panics).</li><li>FP languages in general.</li></ul><p>C++ used to have some form of checked exceptions, you may have noticed it has been deprecated and simplified toward a basic <code>noexcept(&lt;bool&gt;)</code> instead: either a function is declared to possibly throw, or it&#39;s declared never to. Checked exceptions are somewhat problematic in that they lack extensibility, which can cause awkward mappings/nesting. And convoluted exception hierarchies (one of the prime use cases of virtual inheritance is exceptions...).</p><p>In contrast, Go and Rust take the approach that:</p><ul><li>errors should be signaled in band,</li><li>exception should be used for really exceptional situations.</li></ul><p>The latter is rather evident in that (1) they name their exceptions <em>panics</em> and (2) there is no type hierarchy/complicated clause here. The language does not offer facilities to inspect the content of a &#34;panic&#34;: no type hierarchy, no user-defined content, just a &#34;oops, things went so wrong there&#39;s no possible recovery&#34;.</p><p>This effectively encourages users to use proper error handling, whilst still leaving an easy way to bail out in exceptional situations (such as: &#34;wait, I haven&#39;t implement that yet!&#34;).</p><p>Of course, the Go approach unfortunately is much like yours in that you can easily forget to check the error...</p><p>... the Rust approach however is mostly centered around two types:</p><ul><li><code>Option</code>, which is similar to <code>std::optional</code>,</li><li><a href="https://doc.rust-lang.org/std/result/enum.Result.html" rel="noreferrer"><code>Result</code></a>, which is a two possibilities variant: Ok and Err.</li></ul><p>this is much neater because there is no opportunity for accidentally using a result without having checked for success: if you do, the program panics.</p><hr/><p>FP languages form their error handling in constructs which can be split in three layers:
 - Functor
 - Applicative / Alternative
 - Monads / Alternative</p><p>Let&#39;s have a look at Haskell&#39;s <code>Functor</code> typeclass:</p><pre><code>class Functor m where
  fmap :: (a -&gt; b) -&gt; m a -&gt; m b
</code></pre><p>First of all, typeclasses are somewhat similar but not equal to interfaces. Haskell&#39;s function signatures look a bit scary on a first look. But let&#39;s decipher them. The function <code>fmap</code> takes a function as first parameter which is somewhat similar to <code>std::function&lt;a,b&gt;</code>. The next thing is an <code>m a</code>. You can imagine <code>m</code> as something like <code>std::vector</code> and <code>m a</code> as something like <code>std::vector&lt;a&gt;</code>. But the difference is, that <code>m a</code> doesn&#39;t say it has to be explicitly <code>std:vector</code>. So it could be a <code>std::option</code>, too. By telling the language that we have an instance for the typeclass <code>Functor</code> for a specific type like <code>std::vector</code> or <code>std::option</code>, we can use the function <code>fmap</code> for that type. The same must be done for the typeclasses <code>Applicative</code>, <code>Alternative</code> and <code>Monad</code> which allows you to do stateful, possible failing computations. The <code>Alternative</code> typeclass implements error recovery abstractions. By that you can say something like <code>a &lt;|&gt; b</code> meaning it&#39;s either term <code>a</code> or term <code>b</code>. If neither of both computations succeed, it&#39;s still an error.</p><p>Let&#39;s have a look at Haskell&#39;s <code>Maybe</code> type.</p><pre><code>data Maybe a
  = Nothing
  | Just a
</code></pre><p>This means, that where you expect a <code>Maybe a</code>, you get either <code>Nothing</code> or <code>Just a</code>. When looking at <code>fmap</code> from above, an implementation could look like</p><pre><code>fmap f m = case m of
  Nothing -&gt; Nothing
  Just a -&gt; Just (f a)
</code></pre><p>The <code>case ... of</code> expression is called pattern matching and resembles what is known in the OOP world as <code>visitor pattern</code>. Imagine the line <code>case m of</code> as <code>m.apply(...)</code> and the dots is the instantiation of a class implementing the dispatch functions. The lines below the <code>case ... of</code> expression are the respective dispatch functions bringing the fields of the class directly in scope by name. In the <code>Nothing</code> branch we create <code>Nothing</code> and in the <code>Just a</code> branch we name our only value <code>a</code> and create another <code>Just ...</code> with the transformation function <code>f</code> applied to <code>a</code>. Read it as: <code>new Just(f(a))</code>.</p><p>This can now handle erroneous computations while abstracting the actual error checks away. There exist implementations for the other interfaces which makes this kind of computations very powerful. Actually, <code>Maybe</code> is the inspiration for Rust&#39;s <code>Option</code>-Type.</p><hr/><p>I would there encourage you to rework your <code>Success</code> class toward a <code>Result</code> instead. Alexandrescu actually proposed something really close, called <code>expected&lt;T&gt;</code>, for which standard proposals <a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4109.pdf" rel="noreferrer">were made</a>.</p><p>I will stick to the Rust naming and API simply because... it&#39;s documented and works. Of course, Rust has a nifty <code>?</code> suffix operator which would make the code much sweeter; in C++, we&#39;ll use the <code>TRY</code> macro and GCC&#39;s <a href="https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html#Statement-Exprs" rel="noreferrer">statements expression</a> to emulate it.</p><pre><code>template &lt;typename E&gt;
struct Error {
    Error(E e): error(std::move(e)) {}

    E error;
};

template &lt;typename E&gt;
Error&lt;E&gt; error(E e) { return Error&lt;E&gt;(std::move(e)); }

template &lt;typename T, typename E&gt;
struct [[nodiscard]] Result {
    template &lt;typename U&gt;
    Result(U u): ok(true), data(std::move(u)), error() {}

    template &lt;typename F&gt;
    Result(Error&lt;F&gt; f): ok(false), data(), error(std::move(f.error)) {}

    template &lt;typename U, typename F&gt;
    Result(Result&lt;U, F&gt; other):
        ok(other.ok), data(std::move(other.data)),  error(std::move(other.error)) {}

    bool ok = false;
    T data;
    E error;
};

#define TRY(Expr_) \
    ({ auto result = (Expr_); \
       if (!result.ok) { return result; } \
       std::move(result.data); })
</code></pre><p><em>Note: this <code>Result</code> is a placeholder. A proper implementation would use encapsulation and a <code>union</code>. It&#39;s sufficient to get the point across however.</em></p><p>Which allows me to write (<a href="https://ideone.com/3FB7rE" rel="noreferrer">see it in action</a>):</p><pre><code>Result&lt;double, std::string&gt; sqrt(double x) {
    if (x &lt; 0) {
        return error(&#34;sqrt does not accept negative numbers&#34;);
    }
    return x;
}

Result&lt;double, std::string&gt; double_sqrt(double x) {
    auto y = TRY(sqrt(x));
    return sqrt(y);
}
</code></pre><p>which I find really neat:</p><ul><li>unlike the use of error codes (or your <code>Success</code> class), forgetting to check for errors will result in a runtime error<sup>1</sup> rather than some random behavior,</li><li>unlike the use of exceptions, it is apparent <em>at the call site</em> which functions can fail so there&#39;s no surprise.</li><li>with C++-2X standard, we may get <code>concepts</code> in the standard. This would make this kind of programming far more pleasuring as we could leave the choice over the error kind. E.g. with an implementation of <code>std::vector</code> as result, we could compute all possible solutions at once. Or we could choose to improve error handling, as you proposed.</li></ul><p><sup>1</sup> <em>With a properly encapsulated <code>Result</code> implementation ;)</em></p><hr/><p><em>Note: unlike exception, this lightweight <code>Result</code> does not have backtraces, which makes logging less efficient; you may find it useful to at least log the file/line number at which the error message is generated, and to generally write a rich error message. This can be compounded by capturing the file/line each time the <code>TRY</code> macro is used, essentially creating the backtrace manually, or using platform-specific code and libraries such as <code>libbacktrace</code> to list the symbols in the callstack.</em></p><hr/><p>There is one big caveat though: existing C++ libraries, and even <code>std</code>, are based on exceptions. It&#39;ll be an uphill battle to use this style, as any 3rd party library&#39;s API must be wrapped in an adapter...</p></div></div><div class="col-4"></div></div></div></div><div class="col-12 col-md-4"> <ins class="adsbygoogle"
 style="display:block"
 data-ad-client="ca-pub-1731162805004860"
 data-ad-slot="1340983829"
 data-ad-format="auto"
 data-full-width-responsive="true"></ins>   <div class='mt-3 ml-4 border-bottom border-success'><h6><span>Related Question</span></h6></div><ul class='list-group list-group-flush'><li class="list-group-item"><a href='../c-having-error-codes-option-in-c-library-for-performance/'>C++ &#8211; Having error codes option in C++ library for performance</a></li><li class="list-group-item"><a href='../c-rust-style-error-handling-in-c/'>C++ &#8211; Rust-style error handling in C++</a></li><li class="list-group-item"><a href='../c-idiomatic-usage-of-exceptions-in-c/'>C++ &#8211; Idiomatic usage of exceptions in C++</a></li><li class="list-group-item"><a href='../c-how-to-create-and-enforce-contracts-for-exceptions/'>C++ &#8211; How to create and enforce contracts for exceptions</a></li><li class="list-group-item"><a href='../c-exceptions-error-codes-and-discriminated-unions/'>C# &#8211; Exceptions, error codes and discriminated unions</a></li><li class="list-group-item"><a href='../error-handling-in-nest-service-layer/'>Error handling in Nest service layer</a></li></ul></div></div><footer class="entry-footer"></footer></article></div></div></div></main></div></div><footer id="colophon" class="site-footer"><div class="site-info"></div></footer></div>    <script type='text/javascript' src='../../../cdn.jsdelivr.net/npm/mathjax%403/es5/tex-chtml40df.js?ver=5.6' id='mathjax-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/esm/popper.min43d3.js?ver=1.14.7' id='popper-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min5b31.js?ver=4.3.1' id='bootstrap4-js'></script> <script type='text/javascript' id='itectec-common-js-extra'>var globalObject = {"homeUrl":"https:\/\/free-tor-game.com\/"};</script> <script defer src="../../wp-content/cache/autoptimize/4/js/autoptimize_63b39f43631847816e6b0e70ea726624.js"></script></body></html>