<!doctype html><html lang="en-US"><!--  --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- / -->
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">  <link media="all" href="../../wp-content/cache/autoptimize/4/css/autoptimize_dc56928889f08ceb40a4520f8ece953b.css" rel="stylesheet" /><title>Java &#8211; Why don&#8217;t constructor return bool to indicate its success or failure without having to throw an exception &#8211; free-tor-game.com</title> <script>MathJax = {
  tex: {
    inlineMath: [['$','$'],['\\(','\\)']], 
    processEscapes: true
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore|editor-rich-text'
  }
};</script> <link rel='dns-prefetch' href='http://cdn.jsdelivr.net/' /><link rel='dns-prefetch' href='http://cdnjs.cloudflare.com/' /><link rel='dns-prefetch' href='http://stackpath.bootstrapcdn.com/' /><link rel='dns-prefetch' href='http://s.w.org/' /><link rel='stylesheet' id='highlight-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/vs2015.min40df.css?ver=5.6' type='text/css' media='all' /><link rel='stylesheet' id='bootstrap-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.mina352.css?ver=4.1.3' type='text/css' media='all' /><link rel='stylesheet' id='icons-css'  href='../../../stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min40df.css?ver=5.6' type='text/css' media='all' /> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.minb8ff.js?ver=1.12.4' id='jquery-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.minc9a3.js?ver=11.2.0' id='highlight-js'></script>            <script>hljs.highlightAll();</script> <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1731162805004860" crossorigin="anonymous"></script></head><body class="software-template-default single single-software postid-1079403 no-sidebar"><div id="page" class="site"> <a class="skip-link screen-reader-text" href="#content">Skip to content</a><header id="topnav" class="sticky-top"><nav class="navbar navbar-expand-md navbar-light bg-light" role="navigation"> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <a class="navbar-brand" href="#">free-tor-game.com</a><div id="navbar-primary" class="collapse navbar-collapse"><ul id="menu-primary-top-menu" class="nav navbar-nav"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-192" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children dropdown menu-item-192 nav-item"><a title="Tools" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-192">Tools</a><ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-192" role="menu"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-193" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-193 nav-item"><a title="ARFCN-Frequency Converter" href="../../3gpp-arfcn-frequency-converter/" class="dropdown-item">ARFCN-Frequency Converter</a></li></ul></li><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-2301" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2301 nav-item"><a title="Contact Us" href="../../contact/" class="nav-link">Contact Us</a></li></ul></div></nav></header><div id="content" class="site-content"><div id="primary" class="content-area"><main id="main" class="site-main"><div id="main-container" class="container"><div id="main-row" class="row"><div id="main-col" class="col-12"><article id="post-1079403" class="post-1079403 software type-software status-publish hentry category-software tag-c tag-java tag-object-oriented tag-objective-c"><div class="row"><div class="col-12 col-md-8"><header class="entry-header"><h1 class="entry-title text-danger">Java &#8211; Why don&#8217;t constructor return bool to indicate its success or failure without having to throw an exception</h1></header><p style='font-size:1.2em'><span class="mr-2 badge badge-success">c</span><span class="mr-2 badge badge-info">java</span><span class="mr-2 badge badge-warning">object-oriented</span><span class="mr-2 badge badge-primary">objective c</span></p><div class="entry-content"><p>Take C++ constructors for example, we know they don&#39;t return values. Why did Bjarne Stroustrup in the beginning decide <em>not</em> to allow constructor returning &#39;false&#39; to indicate it fails, so that the run time system can destruct its constructed members just like throwing an exception? What are the concerns that make OO language designers decide <em>not</em> to do so? The &#34;new&#34; operator can therefore return &#34;nullptr&#34; if it see constructor returns false. For static objects (in .data/.bss area or on .stack) the compiler generated construction code can still detect and signal, abort or exit accordingly.</p><p>Consider the following two coding paradigms, using dynamic allocation as an example:</p><pre><code>objp = new object; // constructor returns &#39;false&#39;, &#39;new&#39; returns &#39;nullptr&#39;.
if (objp != nullptr) {
    do_something(objp);
} else {
    error_handling();
}
</code></pre><p>compare to:</p><pre><code>try {
    objp = new object; // object throw exception when construction failed
    do_something(objp);
} catch (const typedException &amp;e) {
    error_handling();
}
</code></pre><p>If we need to encode the reason of construction failure, the latter using exception is of course more helpful as we can&#39;t use &#39;objp&#39; to pass any information once construction failed. But if the reason is simple (say &#39;out of memory&#39;), or when skipping error handling does no harm (do_something() might just do decorating), do we really need to involve exception handling in such simple cases? How about allowing both paradigms exist in C++?</p><p>(Another example is, for small embedded C++ compilers if they don&#39;t support exceptions, they can still support &#34;construction fail&#34; handling in this way.)</p><p>Well, maybe my comparison is misleading, I am not against structural exception handling, on the contrary, I <em>LOVE</em> exceptions especially for big systems. But when it comes to small embedded systems where both code and data space are scarce, I think twice.</p><p>The exception handling frames are things similar to setjmp() and longjmp() which are quite expensive in both execution time and memory use; while the (objp==nullptr) comparison takes only a comparison and a jump. Not to mention some of the compilers don&#39;t even support exception handling. In those cases, construction fail can only be dealt with other methods. That reminds me in the old days Turbo Pascal 5.5 OOP can call &#34;Fail&#34; on construction fail, and the newly allocated object will be null.</p><p>What about other languages? Does all OOP languages use exception on construction fail cases?</p><p>Actually, at the time I learnt C++ there is no exception handling available at all (Turbo C++ 3.0/Borland C++ 3.1). Before that I learnt Turbo Pascal 5.5 which supported &#34;Fail&#34; on dynamic construction fail. But when I move to C++ at that time this make me a bit upset since there is no way to test construction fail without defining an Init() function that actually do the inits. Since then I wondered, why can&#39;t constructors return values?</p><p>Now I think maybe returning a value from constructor will make the language &#34;inconsistent&#34;. If we return a value from a constructor and the runtime system test it, this kind of behavior is a lot different from a normal function call since our code can test it. Maybe this kind of inconsistency is not a good idea when designing a programming language? What do you think?</p><hr/><p>In the early days of C++ there was no exception handling, yet Bjarne Stroustrup still didn&#39;t let constructors to return error conditions. Same did the other OO languages at that time (correct me if I am wrong). Therefore, using exception handling <em>was not</em> their original intention to take care of constructor fails. Then why? I think I found the answer, please refer to <a href="https://softwareengineering.stackexchange.com/a/334008/249859">my own answer here</a>. Thanks.</p></div>     <div id="comments" class="comments-area"><div class="row"><div class="col-12"><div class="mt-3 border-bottom border-success"><h4 class="text-success"><i class='fa fa-check-circle text-success mr-3'></i><span>Best Answer</span></h4></div><div class='bg-transparent mb-3'><p>Your question indicates a fundamental misunderstanding of the value of the exception mechanism.  If the language in question didn&#39;t have exceptions, then of course, error codes would be the only way to go.  But using error codes in a language that supports exceptions is not often the right answer.</p><p>Why?</p><p>As it turns out, very often, code really close to the source of a show stopping problem doesn&#39;t know what to do when that happens.</p><p>Since the code close to the error often doesn&#39;t know what to do, there is nothing for that code to do to handle the error except let someone else do that.</p><p>With error code returns, every caller must check for errors, even though there is usually nothing they can do but to further propagate the error to their callers (lather, rinse, repeat...)</p><h3> Enter Exception Handling</h3><p>Exception handling is a mechanism that allows a separation of the callees that have problems from truly capable error handlers, which are typically rather removed from the source of an error.</p><p>Good handlers know how to abort or retry the broader computation being performed, not simply log the error and propagate the error up the call chain.  A sign of a good handler is that it doesn&#39;t need to propagate errors up the call chain because it <em>handled</em> them.</p><p>With exception handling, we typically don&#39;t surround individual method calls with exception handling, <em>and that includes constructors and new operations</em>.</p><p>Exception handling allows better definition of an exception handler, and at a considerable distance away from the source of the exception, and this is an advantage because such distance usually means a better understanding of what to do in case of errors.</p><p>(Exception handling also allows structuring errors, but we&#39;ll leave that for another discussion.)</p><hr/><p>If we haven&#39;t convinced you yet compare these code sequences:</p><pre><code>objp = new object (); // constructor returns &#39;false&#39;, &#39;new&#39; returns &#39;nullptr&#39;.
if (objp != nullptr) {
    do_something(objp);
} else {
    error_handling();
}
</code></pre><p>with:</p><pre><code>objp = new object (); // object throw exception when construction failed
</code></pre><p>The latter, using exceptions, is much cleaner and more appropriate to an arguable majority of use cases.</p></div></div><div class="col-4"></div></div></div></div><div class="col-12 col-md-4"> <ins class="adsbygoogle"
 style="display:block"
 data-ad-client="ca-pub-1731162805004860"
 data-ad-slot="1340983829"
 data-ad-format="auto"
 data-full-width-responsive="true"></ins>   <div class='mt-3 ml-4 border-bottom border-success'><h6><span>Related Question</span></h6></div><ul class='list-group list-group-flush'><li class="list-group-item"><a href='../java-why-does-java-exit-with-success-after-an-uncaught-exception/'>Java &#8211; Why does Java exit with success after an uncaught exception</a></li><li class="list-group-item"><a href='../object-oriented-should-i-throw-exception-from-constructor/'>Object-oriented &#8211; should I throw exception from constructor</a></li><li class="list-group-item"><a href='../java-learning-to-write-dsls-utilities-for-unit-tests-and-am-worried-about-extensablity/'>Java &#8211; Learning to write DSLs utilities for unit tests and am worried about extensablity</a></li><li class="list-group-item"><a href='../java-should-a-getter-throw-an-exception-if-its-object-has-invalid-state/'>Java &#8211; Should a getter throw an exception if its object has invalid state</a></li><li class="list-group-item"><a href='../java-why-throw-exception-that-is-subclass-of-another-exception-also-thrown/'>Java &#8211; Why throw exception that is subclass of another exception also thrown</a></li><li class="list-group-item"><a href='../java-should-constructors-ever-be-used-only-for-side-effects/'>Java &#8211; Should constructors ever be used only for side-effects</a></li><li class="list-group-item"><a href='../c-error-handling-considerations/'>C++ &#8211; Error handling considerations</a></li></ul></div></div><footer class="entry-footer"></footer></article></div></div></div></main></div></div><footer id="colophon" class="site-footer"><div class="site-info"></div></footer></div>    <script type='text/javascript' src='../../../cdn.jsdelivr.net/npm/mathjax%403/es5/tex-chtml40df.js?ver=5.6' id='mathjax-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/esm/popper.min43d3.js?ver=1.14.7' id='popper-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min5b31.js?ver=4.3.1' id='bootstrap4-js'></script> <script type='text/javascript' id='itectec-common-js-extra'>var globalObject = {"homeUrl":"https:\/\/free-tor-game.com\/"};</script> <script defer src="../../wp-content/cache/autoptimize/4/js/autoptimize_63b39f43631847816e6b0e70ea726624.js"></script></body></html>