<!doctype html><html lang="en-US"><!--  --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- / -->
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">  <link media="all" href="../../wp-content/cache/autoptimize/4/css/autoptimize_dc56928889f08ceb40a4520f8ece953b.css" rel="stylesheet" /><title>C++ &#8211; Augment a thrown exception with some contextual information &#8211; free-tor-game.com</title> <script>MathJax = {
  tex: {
    inlineMath: [['$','$'],['\\(','\\)']], 
    processEscapes: true
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore|editor-rich-text'
  }
};</script> <link rel='dns-prefetch' href='http://cdn.jsdelivr.net/' /><link rel='dns-prefetch' href='http://cdnjs.cloudflare.com/' /><link rel='dns-prefetch' href='http://stackpath.bootstrapcdn.com/' /><link rel='dns-prefetch' href='http://s.w.org/' /><link rel='stylesheet' id='highlight-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/vs2015.min40df.css?ver=5.6' type='text/css' media='all' /><link rel='stylesheet' id='bootstrap-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.mina352.css?ver=4.1.3' type='text/css' media='all' /><link rel='stylesheet' id='icons-css'  href='../../../stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min40df.css?ver=5.6' type='text/css' media='all' /> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.minb8ff.js?ver=1.12.4' id='jquery-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.minc9a3.js?ver=11.2.0' id='highlight-js'></script>            <script>hljs.highlightAll();</script> <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1731162805004860" crossorigin="anonymous"></script></head><body class="software-template-default single single-software postid-1085855 no-sidebar"><div id="page" class="site"> <a class="skip-link screen-reader-text" href="#content">Skip to content</a><header id="topnav" class="sticky-top"><nav class="navbar navbar-expand-md navbar-light bg-light" role="navigation"> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <a class="navbar-brand" href="#">free-tor-game.com</a><div id="navbar-primary" class="collapse navbar-collapse"><ul id="menu-primary-top-menu" class="nav navbar-nav"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-192" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children dropdown menu-item-192 nav-item"><a title="Tools" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-192">Tools</a><ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-192" role="menu"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-193" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-193 nav-item"><a title="ARFCN-Frequency Converter" href="../../3gpp-arfcn-frequency-converter/" class="dropdown-item">ARFCN-Frequency Converter</a></li></ul></li><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-2301" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2301 nav-item"><a title="Contact Us" href="../../contact/" class="nav-link">Contact Us</a></li></ul></div></nav></header><div id="content" class="site-content"><div id="primary" class="content-area"><main id="main" class="site-main"><div id="main-container" class="container"><div id="main-row" class="row"><div id="main-col" class="col-12"><article id="post-1085855" class="post-1085855 software type-software status-publish hentry category-software tag-c tag-clean-code tag-coding-style tag-error-handling tag-exceptions"><div class="row"><div class="col-12 col-md-8"><header class="entry-header"><h1 class="entry-title text-danger">C++ &#8211; Augment a thrown exception with some contextual information</h1></header><p style='font-size:1.2em'><span class="mr-2 badge badge-success">c</span><span class="mr-2 badge badge-info">clean code</span><span class="mr-2 badge badge-warning">coding-style</span><span class="mr-2 badge badge-primary">error handling</span><span class="mr-2 badge badge-danger">exceptions</span></p><div class="entry-content"><p>The application this question is about is basically a transpiler which contains a lot of logic. The transpiler is written in C++ (which should not be much of relevance for this question), and it transpiles a special language (which we developed) into a different language.</p><p>For error handling (errors originating in invalid input as well as internal errors of the transpiler), I use exceptions. To keep the transpiler&#39;s logic as simple as possible, the input is validated very late, i.e. in most cases no separate validation is taking place. This means, the processing logic throws exceptions. Some utility functions are used globally thoughout the code base, and those can throw exceptions, too.</p><p>That means, exceptions are potentially thrown in a utility function, in which we do not know where the input comes from. That is a problem, because &#8212; similar to how your compiler tells you in which line of which file the parse error occurred &#8212; I&#39;d like to tell the user of the transpiler where the error originated. To keep things simple, that does not necessarily have to be some &#34;stack&#34; or &#34;chain&#34; of contexts. But the exceptions should carry at least <em>some contextual information</em>, which part of the input is invalid and why, such that the relevant part of the input can be corrected and/or an IDE can navigate to the error&#39;s source.</p><p>For the exceptions, I currently use one single class <code>Error</code> which carries all information as members, and static functions are used to create them depending on what error occurred, for example:</p><pre><code>throw Error::internalError(&#34;This should not have happened...&#34;);
</code></pre><p>or a more interesting case (pseudo code, this is not C++):</p><pre><code>var x = ...;
if (!x.isInteger())
    throw Error::notAnInteger(x);
</code></pre><p>Now I&#39;d like to augment that exception (the <code>Error</code> object) with a &#34;context / location specification&#34;. For example, in my transpiled language, I have the concept of variables, which have some predefined value. Let&#39;s consider a variable which has an internal ID stored as an integer, and a value which we can retrieve. Now we want to make sure that the value is an integer (again, pseudo code):</p><pre><code>var variableID = ...;
var value = getValueOfVariable(variableID);
if (!value.isInteger())
    throw Error::notAnInteger(value);
</code></pre><p>Now consider the case where <code>variableID = 42, value = &#34;foo&#34;</code>. When the exception will be thrown and presented to the user, she only knows that <code>&#34;foo&#34;</code> is not an integer, but she is not being told that this value comes from the variable <code>42</code>.</p><p>That&#39;s why I want to tell the <code>Error</code> somehow that we are trying to parse the variable whose ID is <code>variableID</code>.</p><p>I&#39;d like to present you three ideas which I came up with, but can&#39;t decide which one is better style.</p><hr/><p><strong>The first idea</strong> is to add additional static functions, each for a type of such a context. In the example above, instead of</p><pre><code>    throw Error::notAnInteger(value);
</code></pre><p>I then do</p><pre><code>    throw Error::variableNotAnInteger(value, variableID);
</code></pre><p>and within that function I store the information that the error source was &#34;variable with ID <code>variableID</code>&#34;. However, with more and more such types of contexts (it is not only parsing the value of a variable which can lead to &#34;not an integer&#34; errors), the number of functions grows rapidly.</p><hr/><p><strong>A second idea</strong> was to introduce a <code>Location</code> class, which has the purpose of describing the error source / context, and pass that along with the other parameters to these static functions:</p><pre><code>    throw Error::notAnInteger(value, Location::variable(variableID));
</code></pre><p>However, that means that all utility functions (for example a function which has only the purpose to parse a value, independently of where the value comes from), would need to be augmented with the contextual <code>Location</code> object, in order to<br /> appropriately construct the <code>Error</code> object to be thrown. That however makes the code base kind of ugly, in particular for nested and further nested logic.</p><hr/><p><strong>A third idea</strong> is to add the location <em>after the exception was thrown</em>. The utility function throws an exception, and the caller then catches the exception, adds the appropriate location, and then throws the augmented exception again. This has the drawback that when I forget somewhere in the code base to add such a location, the error does not carry one. (In contrast, the second idea makes sure that a location object is being passed.)</p><p>This would look like that (again, pseudo code):</p><pre><code>function parseValue(value, type) {
    ...
    if (type == &#34;integer&#34;) {
        if (!value.isInteger()) {
            // Throw an exception without a location / context information:
            throw Error::notAnInteger(value);
        }
        return value.toInteger();
    }
    ...
}

//-----------------------------------------

var variableID = ...;
var value = getValueOfVariable(variableID);
var type = getTypeOfVariable(variableID);
try {
    var parsedValue = parseValue(value, type);
} catch (Error e) {
    // Add the location of the error, and rethrow:
    e.setLocation(Location::variable(variableID));
    throw e;
}
</code></pre><hr/><p><strong>Which of the above methods can be considered a good style? Is there even a fourth option I should consider? How is this typically done in trans-/compilers?</strong></p></div>     <div id="comments" class="comments-area"><div class="row"><div class="col-12"><div class="mt-3 border-bottom border-success"><h4 class="text-success"><i class='fa fa-check-circle text-success mr-3'></i><span>Best Answer</span></h4></div><div class='bg-transparent mb-3'><p>Using the backtrace is the best option. There is a proposal to embed the backtrace information into the exception (see it <a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3441.html" rel="nofollow noreferrer">here</a>), but so far nothing is done. To get the backtrace information, you can do like explained in <a href="https://stackoverflow.com/a/77336/476681">this answer</a>.</p><p>If you use boost exceptions, then you can use <a href="http://www.boost.org/doc/libs/1_55_0/libs/exception/doc/diagnostic_information.html" rel="nofollow noreferrer">their diagnostics</a>.</p></div></div><div class="col-4"></div></div></div></div><div class="col-12 col-md-4"> <ins class="adsbygoogle"
 style="display:block"
 data-ad-client="ca-pub-1731162805004860"
 data-ad-slot="1340983829"
 data-ad-format="auto"
 data-full-width-responsive="true"></ins>   <div class='mt-3 ml-4 border-bottom border-success'><h6><span>Related Question</span></h6></div><ul class='list-group list-group-flush'><li class="list-group-item"><a href='../c-having-error-codes-option-in-c-library-for-performance/'>C++ &#8211; Having error codes option in C++ library for performance</a></li><li class="list-group-item"><a href='../throwing-an-exception-inside-finally/'>Throwing an exception inside finally</a></li><li class="list-group-item"><a href='../java-better-way-to-define-an-exception-thrown-by-a-method-in-java/'>Java &#8211; better way to define an exception thrown by a method in Java</a></li><li class="list-group-item"><a href='../java-why-throw-exception-that-is-subclass-of-another-exception-also-thrown/'>Java &#8211; Why throw exception that is subclass of another exception also thrown</a></li><li class="list-group-item"><a href='../c-exception-hierarchy-and-use-of-what-message-for-parsing-strings/'>C++ &#8211; Exception Hierarchy and Use of What Message for Parsing Strings</a></li></ul></div></div><footer class="entry-footer"></footer></article></div></div></div></main></div></div><footer id="colophon" class="site-footer"><div class="site-info"></div></footer></div>    <script type='text/javascript' src='../../../cdn.jsdelivr.net/npm/mathjax%403/es5/tex-chtml40df.js?ver=5.6' id='mathjax-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/esm/popper.min43d3.js?ver=1.14.7' id='popper-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min5b31.js?ver=4.3.1' id='bootstrap4-js'></script> <script type='text/javascript' id='itectec-common-js-extra'>var globalObject = {"homeUrl":"https:\/\/free-tor-game.com\/"};</script> <script defer src="../../wp-content/cache/autoptimize/4/js/autoptimize_63b39f43631847816e6b0e70ea726624.js"></script></body></html>